### PR TITLE
fix(lark): not compare verification token if undefined

### PR DESCRIPTION
**Pull request by MaikoTan**
fix koishijs/koishi#1067

### CODE REVIEW

**Review by shigma — COMMENTED** [review]
如果没有 token 岂不是就没有鉴权了？

**Comment by MaikoTan** [comment]
> 如果没有 token 岂不是就没有鉴权了？

Unfortunately, there's only "challenge" message and "interactive card action" message would be sent with the token that can be verified.

**Comment by shigma** [comment]
是说其他事件都可以被伪造吗

**Comment by MaikoTan** [comment]
> 是说其他事件都可以被伪造吗
> 

Yes, but there is `encryptKey` that can be a security guard for them.

**Pull request merged**
