### PR TITLE
feat(feishu): refresh token every 1 hour

### PR DESCRIPTION
**Pull request by MaikoTan**
to make it always actively.

### CODE REVIEW

**Comment by TimeBather** [comment]
OK , I will test it tonight

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by TimeBather** [comment]
It seems that the referesh task per hour runs correctly. I'll test the availablity of the token next.

**Comment by TimeBather** [comment]
I think it's OK in my test. It refreshed the token successfully. And the message could been send to the channel after about 3 hours.

**Comment by MaikoTan** [comment]
Okay, but it is required to `Approve` this PR before merging it.

**Pull request merged**
